language: csharp
solution: Taskin.sln
dotnet: 2.2.101
dist: xenial
mono: none
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  - provider: script
    script: bash scripts/deploy.sh
